module.exports = {
  USERS_COLLECTION:                       'users',
  USERS_DELIVERY_COLLECTION:              'users_public',
  USERS_PUBLIC_COLLECTION:                'users_public',
  USER_CARTS_COLLECTION:                  'user_carts',
  USER_CART_ITEMS_SUB_COLLECTION:         'cart_items',
  SUGGESTS_BASIC_COLLECTION:              'suggests_basic',
  SELLERS_COLLECTION:                     'sellers',
  SELLERS_BASIC_COLLECTION:               'sellers_basic',
  SELLER_ITEMS_SUB_COLLECTION:            'items',
  SELLER_ITEMS_BASIC_SUB_COLLECTION:      'items_basic',
  SELLER_CATALOGS_SUB_COLLECTION:         'catalogs',
  BROADCAST_MESSAGES_COLLECTION:          'broadcast_messages',
  NOTIFICATION_TOKENS_COLLECTION:         'notification_tokens',
  USER_PHOTOS_FOLDER:                     'user_photos',
  SELLER_PHOTOS_FOLDER:                   'seller_photos',
};